name: web-crawler-ci-cd

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t web_crawler .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag web_crawler ${{ secrets.DOCKER_USERNAME }}/web_crawler
          docker push ${{ secrets.DOCKER_USERNAME }}/web_crawler

      - name: Run the app
        run: docker run ${{ secrets.DOCKER_USERNAME }}/web_crawler
